name: infra-security

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.53.0

      - name: TFLint Init
        run: tflint --init

      - name: TFLint Run
        run: tflint -f compact

      - name: Install Checkov
        run: pipx install checkov

      - name: Checkov Scan
        run: checkov -d . --framework terraform --quiet --compact
