name: terratest-local

on:
  workflow_dispatch:
  pull_request:

jobs:
  terratest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Start LocalStack
        run: |
          docker run -d --name localstack_main \
            -p 4566:4566 -p 4510-4559:4510-4559 \
            -e SERVICES=lambda,ssm,iam,sts,logs,cloudwatch \
            -v /var/run/docker.sock:/var/run/docker.sock \
            localstack/localstack

      - name: Wait for LocalStack
        run: |
          for i in {1..30}; do curl -s http://localhost:4566/_localstack/health && break || sleep 2; done

      - name: Run Terratest
        env:
          LOCALSTACK: '1'
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_REGION: eu-west-2
        run: |
          go mod download
          go test ./test -v -timeout 45m
